openapi: 3.0.0
info:
  title: GoodPill Pharmacy Automation
  description: Integrate Pharmacy User tools into the exisitng Pharmacy Automation app
  version: 0.0.1

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://gppa.goodpill.org/v1
    description: The production API

tags:
    - name: Authentication
      description: Authenticate with goodpill
    - name: Orders
      description: Working with orders

paths:
  /auth:
    get:
      tags:
      - Authentication
      summary: Generates a set of authentication tokens
      description: Used to generate the 2 primary tokens needed to access the api.  If you are successful, you will receive a auth and refresh token.  The auth token is used for all basic requests and has a 10 minute lifespan.  The refresh token is a single use token that has a 30 day lifespan.  It can only be used to request a new auth token.
      security:
        - BasicAuth: []
      responses:
        '200':    # status code
          description: The authentication tokens needed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                  data:
                    type: object
                    properties:
                      auth:
                        type: string
                        description: The Authentication token.  This should be passed for all future data calls.  The auth token has a 10 minute TTL
                      refresh:
                        type: string
                        description: This is a single use token that is only good to create a new token set.  The refresh token has a 30 day TTL
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: failure

  /auth/refresh:
    get:
      tags:
      - Authentication
      summary: Get a fresh token set without username/password
      description: Use a refresh token to generate an entire new set of authentication tokens.
      security:
        - BearerAuth: []
      responses:
        '200':    # status code
          description: The authentication tokens needed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
                  data:
                    type: object
                    properties:
                      auth:
                        type: string
                        description: The Authentication token.  This should be passed for all future data calls.  The auth token has a 10 minute TTL
                      refresh:
                        type: string
                        description: This is a single use token that is only good to create a new token set.  The refresh token has a 30 day TTL
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: failure

  /order/{invoice_number}/shipped:
    post:
      summary: Mark an invoice as shipped
      description: Used to mark and invoice as shippend.  Will update the invoice and send appropriate communications to the patient.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: invoice_number
          schema:
            type: integer
          required: true
          description: The invoice we are attempting to update.  This is invoice_number not order number.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ship_date:
                  type: integer
                  format: date
                  description: An EST based date for when the package was shipped
                tracking_number:
                  type: string
                  description: The tracking number for the label created for the shipment
      responses:
        '200':
          description: The order was updated and patient notifications were setn
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
        '400':
          description: There was a problem with the request.  Please see the desc property for more details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: failure
                  desc:
                    type: string

        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: failure

  /order/{invoice_number}/delivered:
    post:
      summary: Mark an invoice as delivered
      description: Used to mark and invoice as delivered.  Will update the invoice and send appropriate communications to the patient.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: invoice_number
          schema:
            type: integer
          required: true
          description: The invoice we are attempting to update.  This is invoice_number not order number.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deliverd_date:
                  type: integer
                  format: date
                  description: An EST based date for when the package was shipped
                tracking_number:
                  type: string
                  description: The tracking number for the label created for the shipment
      responses:
        '200':
          description: The order was updated and patient notifications were setn
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: success
        '400':
          description: There was a problem with the request.  Please see the desc property for more details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: failure
                  desc:
                    type: string

        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: failure
